// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwhLbUNNeIVd5YE_c5NcYX2wDvrZNNXzg',
    appId: '1:810398474537:web:40125359ca173a731c5738',
    messagingSenderId: '810398474537',
    projectId: 'assessment-tracker-780a9',
    authDomain: 'assessment-tracker-780a9.firebaseapp.com',
    storageBucket: 'assessment-tracker-780a9.appspot.com',
    measurementId: 'G-8PX052K647',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvG_PeQuUSaSOqT1LeCf2k5jxPnRHw0cs',
    appId: '1:810398474537:android:edfc8635cfc6d0351c5738',
    messagingSenderId: '810398474537',
    projectId: 'assessment-tracker-780a9',
    storageBucket: 'assessment-tracker-780a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb8RWRwIzbgYRAj0UifFgOK2utLCSBS7A',
    appId: '1:810398474537:ios:636f9d64ad56ced41c5738',
    messagingSenderId: '810398474537',
    projectId: 'assessment-tracker-780a9',
    storageBucket: 'assessment-tracker-780a9.appspot.com',
    iosBundleId: 'com.example.digitalSchoolAssesment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb8RWRwIzbgYRAj0UifFgOK2utLCSBS7A',
    appId: '1:810398474537:ios:636f9d64ad56ced41c5738',
    messagingSenderId: '810398474537',
    projectId: 'assessment-tracker-780a9',
    storageBucket: 'assessment-tracker-780a9.appspot.com',
    iosBundleId: 'com.example.digitalSchoolAssesment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwhLbUNNeIVd5YE_c5NcYX2wDvrZNNXzg',
    appId: '1:810398474537:web:111c81ff312d6d241c5738',
    messagingSenderId: '810398474537',
    projectId: 'assessment-tracker-780a9',
    authDomain: 'assessment-tracker-780a9.firebaseapp.com',
    storageBucket: 'assessment-tracker-780a9.appspot.com',
    measurementId: 'G-FYVS12XNCB',
  );

}